site_name: 우분투한국커뮤니티 공시
site_name_short: 공시
site_base_url: "https://disclosures.ubuntu-kr.org/"
site_url: "https://disclosures.ubuntu-kr.org/"
copyright: |
  © 2021-2023 우분투 한국 커뮤니티 (우분투 한국 로컬 커뮤니티 팀).
  별도 고지가 있는 경우를 제외하고, 웹 사이트 소스코드는 MIT, 웹 사이트의 컨텐츠는 CC BY-SA 4.0 라이선스로 이용 가능합니다.
  Ubuntu 및 Canonical 은 Canonical Ltd. 의 등록 상표입니다.
repo_url: https://github.com/ubuntu-kr/disclosures.ubuntu-kr.org
repo_name: ubuntu-kr/disclosures.ubuntu-kr.org
contact_email: contact@ubuntu-kr.org
theme:
    name: null
    custom_dir: 'theme_ubuntu/'
    static_templates:
      - "search_index.json"
plugins:
    - search
nav:
  - 홈: index.md
  - 정관 및 세칙: 
    - legal/index.md
    - 정관:
      - legal/articles-of-incorporation/index.md
      - legal/articles-of-incorporation/history.md
    - 선거관리규약:
      - legal/election-bylaw/index.md
      - legal/election-bylaw/history.md
    - 회비규정:
      - legal/membership-fee-regulation/index.md
      - legal/membership-fee-regulation/history.md
  - 개인정보처리방침: 
    - privacy-policy/index.md
    - privacy-policy/online.md
    - privacy-policy/uck23.md
  - 회계자료: 
    - finance/index.md
    - "2022":
      - finance/2022/index.md
  - 운영진:
    - organizers/index.md
    - organizers/gen2.md
    - organizers/gen3.md
    - organizers/gen4.md
    - organizers/gen5.md
    - organizers/gen6.md
  - 회의록: 
    - meetings/index.md
    - meetings/rga2023/index.md
  - ubuntu-kr.org: https://ubuntu-kr.org